-- 金門大學校務系統 MVP 假資料
-- 產生時間: 2026-09-11 16:57:54

-- 科系資料
INSERT INTO departments (dept_id, dept_code, dept_name) VALUES (1, 'CSIE', '資訊工程學系');
INSERT INTO departments (dept_id, dept_code, dept_name) VALUES (2, 'EE', '電機工程學系');
INSERT INTO departments (dept_id, dept_code, dept_name) VALUES (3, 'ME', '機械工程學系');
INSERT INTO departments (dept_id, dept_code, dept_name) VALUES (4, 'BA', '企業管理學系');
INSERT INTO departments (dept_id, dept_code, dept_name) VALUES (5, 'TM', '觀光管理學系');

-- 教師帳號 (密碼: teacher123)
INSERT INTO users (user_id, username, password_hash, full_name, role, dept_id, email) VALUES (1, 'T001', '$2b$12$X8UQbmDrfjYtf9YpLHhl5O7hE4.OZnINwBeC4scDM5yE./q8eHtyi', '王大明', 'TEACHER', 1, 't001@nqu.edu.tw');
INSERT INTO users (user_id, username, password_hash, full_name, role, dept_id, email) VALUES (2, 'T002', '$2b$12$xdygFG7fP6dalb.7qosg4eIWiHoBFV3YHXjaTzXb2jMMHB9eNSrm.', '李小華', 'TEACHER', 1, 't002@nqu.edu.tw');
INSERT INTO users (user_id, username, password_hash, full_name, role, dept_id, email) VALUES (3, 'T003', '$2b$12$zVLW27XPK2zIOBjEy3L9U.O1gibLCgxh7bHVpvhZC27w3XQyTmC4G', '張志偉', 'TEACHER', 2, 't003@nqu.edu.tw');
INSERT INTO users (user_id, username, password_hash, full_name, role, dept_id, email) VALUES (4, 'T004', '$2b$12$tvgryRcGDxdiWVedde6gheP/6vOfITLjvfHapfh3GqHkaLZrMEz92', '陳美玲', 'TEACHER', 2, 't004@nqu.edu.tw');
INSERT INTO users (user_id, username, password_hash, full_name, role, dept_id, email) VALUES (5, 'T005', '$2b$12$45nSvp1bLOVVo6NaMwRyK.FU4DOY.kEvvdYOP6xwJLYMxCm.WJ6R2', '林俊傑', 'TEACHER', 3, 't005@nqu.edu.tw');
INSERT INTO users (user_id, username, password_hash, full_name, role, dept_id, email) VALUES (6, 'T006', '$2b$12$Em0gKIIg7O39ewT1JOtQWOtMIjK.I26AwWMb4Mivzd8pu77UAhF.W', '黃雅芬', 'TEACHER', 3, 't006@nqu.edu.tw');
INSERT INTO users (user_id, username, password_hash, full_name, role, dept_id, email) VALUES (7, 'T007', '$2b$12$XGV6FwaUrPSsQ5ObEW42/eHVC8PX1RuvMwoXMhE3ZsPyD.ar9bBGC', '劉建宏', 'TEACHER', 4, 't007@nqu.edu.tw');
INSERT INTO users (user_id, username, password_hash, full_name, role, dept_id, email) VALUES (8, 'T008', '$2b$12$lwbXuUp6YMkP/E7B8u39C.NksySBR9CoGg3b8xKNQR4W4lsqBOhva', '吳佳琳', 'TEACHER', 4, 't008@nqu.edu.tw');
INSERT INTO users (user_id, username, password_hash, full_name, role, dept_id, email) VALUES (9, 'T009', '$2b$12$9l/4DefnUATqLBKhCcH9ROrgu4zF4rYRbk.r2IgJxsjMUxsPj5bey', '鄭明哲', 'TEACHER', 5, 't009@nqu.edu.tw');
INSERT INTO users (user_id, username, password_hash, full_name, role, dept_id, email) VALUES (10, 'T010', '$2b$12$ZKvFoR/FEREQ.KbAq5mHjuXPW30hgNarfSeA0qzCNQ0sKUFSySqJy', '蔡雅婷', 'TEACHER', 5, 't010@nqu.edu.tw');

-- 學生帳號 (密碼: student123)
INSERT INTO users (user_id, username, password_hash, full_name, role, dept_id, email) VALUES (11, '11303001', '$2b$12$bKX6arkNsgjzi/eRjESFdegiQL3CusoNkWdYY0OfmS7mbX0D2jpoS', '陳小明', 'STUDENT', 1, '11303001@stu.nqu.edu.tw');
INSERT INTO users (user_id, username, password_hash, full_name, role, dept_id, email) VALUES (12, '11303002', '$2b$12$6LL1HH.5WUBV4LZX1pUpNeZWMO/XE.ktbtrtkxjCh8X.QXEy4kU/m', '林小華', 'STUDENT', 1, '11303002@stu.nqu.edu.tw');
INSERT INTO users (user_id, username, password_hash, full_name, role, dept_id, email) VALUES (13, '11303003', '$2b$12$1yjV3FkXMbR8zXGMnEcxyOOh/DKYQ8DuT98sAn.hyqDJSYKD8HVvO', '張小強', 'STUDENT', 1, '11303003@stu.nqu.edu.tw');
INSERT INTO users (user_id, username, password_hash, full_name, role, dept_id, email) VALUES (14, '11303004', '$2b$12$sCMTvAAnqxkpWBf5Qg9Kzebzx911afOTWQZyQ.wOKK/I9UOl5gj12', '王小美', 'STUDENT', 1, '11303004@stu.nqu.edu.tw');
INSERT INTO users (user_id, username, password_hash, full_name, role, dept_id, email) VALUES (15, '11303005', '$2b$12$q.xDufQVVAgo6lZQhx./au3OnUWUxdW26h3VPOBhKra3s9cUsalOy', '李小莉', 'STUDENT', 1, '11303005@stu.nqu.edu.tw');
INSERT INTO users (user_id, username, password_hash, full_name, role, dept_id, email) VALUES (16, '11303006', '$2b$12$11./xOhVDDCZdvga0Z/Xdeerw0ahfVYLcyAMM0RBHY/AIW6QLxC.y', '黃小偉', 'STUDENT', 1, '11303006@stu.nqu.edu.tw');
INSERT INTO users (user_id, username, password_hash, full_name, role, dept_id, email) VALUES (17, '11306001', '$2b$12$rEAvStoE.ASaGR/4RAMN/OEiK5czSMGz55.zFB6zD44ZOCg7QA5bm', '劉志豪', 'STUDENT', 2, '11306001@stu.nqu.edu.tw');
INSERT INTO users (user_id, username, password_hash, full_name, role, dept_id, email) VALUES (18, '11306002', '$2b$12$LqnW1xQvzIG2Atk8SC/afO9TwFfwbZ9MfrXZ1I865IIBZ3siTF0X2', '陳雅芳', 'STUDENT', 2, '11306002@stu.nqu.edu.tw');
INSERT INTO users (user_id, username, password_hash, full_name, role, dept_id, email) VALUES (19, '11306003', '$2b$12$S.rdrd08osZzl9q1.7pneuNjYqc7xSpBv0xu01u6bAvxsAOUmADNy', '林俊宏', 'STUDENT', 2, '11306003@stu.nqu.edu.tw');
INSERT INTO users (user_id, username, password_hash, full_name, role, dept_id, email) VALUES (20, '11306004', '$2b$12$YHQQC/4g6DMwhJANkZREpeG/gNOPD82yvjrzi6Pb6Bwo8PSnpGF6O', '張美玲', 'STUDENT', 2, '11306004@stu.nqu.edu.tw');
INSERT INTO users (user_id, username, password_hash, full_name, role, dept_id, email) VALUES (21, '11306005', '$2b$12$XIIqzUrZTLLNQAEf4QJsDe6u54i5IYoCZ2vhXwDGJzgiSbLZGBmYy', '王建平', 'STUDENT', 2, '11306005@stu.nqu.edu.tw');
INSERT INTO users (user_id, username, password_hash, full_name, role, dept_id, email) VALUES (22, '11306006', '$2b$12$OFO275riMAGA3mFg0oFgweR2wrIXshmljoGuPXT/nYIucNyHQuQwi', '李小娟', 'STUDENT', 2, '11306006@stu.nqu.edu.tw');
INSERT INTO users (user_id, username, password_hash, full_name, role, dept_id, email) VALUES (23, '11308001', '$2b$12$FhBGLrm3G7ogCIJ8xva2RuINsMjM0077ymNwjlAaaDoFoiyTu4kU6', '黃志偉', 'STUDENT', 3, '11308001@stu.nqu.edu.tw');
INSERT INTO users (user_id, username, password_hash, full_name, role, dept_id, email) VALUES (24, '11308002', '$2b$12$VMtkxfceCjpx1u25IW/1UOsvTxxLbzrgtWhB.pjGv//UfRXk34iH2', '林美慧', 'STUDENT', 3, '11308002@stu.nqu.edu.tw');
INSERT INTO users (user_id, username, password_hash, full_name, role, dept_id, email) VALUES (25, '11308003', '$2b$12$1eZk3PTIGYNkRYKEpAthWeSIh9nfvWOh4dVoALYvKmwfdsKv8BHri', '張家豪', 'STUDENT', 3, '11308003@stu.nqu.edu.tw');
INSERT INTO users (user_id, username, password_hash, full_name, role, dept_id, email) VALUES (26, '11308004', '$2b$12$mn/jfSUSpD4Q/cP.jkZeLuL1tIyrTUWaFEZkVQrZUPgXPHV8bIrcy', '陳小雲', 'STUDENT', 3, '11308004@stu.nqu.edu.tw');
INSERT INTO users (user_id, username, password_hash, full_name, role, dept_id, email) VALUES (27, '11308005', '$2b$12$oT0pC3i9yeE0ygmwzj/Ak.Wn3hcGfje2pzIBuXIq/kBgn2ANHOxSe', '王大同', 'STUDENT', 3, '11308005@stu.nqu.edu.tw');
INSERT INTO users (user_id, username, password_hash, full_name, role, dept_id, email) VALUES (28, '11308006', '$2b$12$RROzYwuT9FNMIdIWTtXf8eYEOlTMAvxVNcnvmSjpk9fZldNnsv0Y2', '李志明', 'STUDENT', 3, '11308006@stu.nqu.edu.tw');
INSERT INTO users (user_id, username, password_hash, full_name, role, dept_id, email) VALUES (29, '11312001', '$2b$12$OHDngWxOJrWixp/fym9Ywu7maCHOhUTqgOqJexXwVulsCgm0jceaq', '劉美玲', 'STUDENT', 4, '11312001@stu.nqu.edu.tw');
INSERT INTO users (user_id, username, password_hash, full_name, role, dept_id, email) VALUES (30, '11312002', '$2b$12$OOGboeA/Qz8hN2QTW4lMVuHZhvzelKNOo0mljLD8R2p.J2uNibdIa', '陳建志', 'STUDENT', 4, '11312002@stu.nqu.edu.tw');
INSERT INTO users (user_id, username, password_hash, full_name, role, dept_id, email) VALUES (31, '11312003', '$2b$12$Spe6QTN7dEBzltGAJRbrMOTR1WhLzqP1HRSUwM2S9/HlqZqNxedQO', '林小芬', 'STUDENT', 4, '11312003@stu.nqu.edu.tw');
INSERT INTO users (user_id, username, password_hash, full_name, role, dept_id, email) VALUES (32, '11312004', '$2b$12$ET4kx8dLKEt/hIB2JZo88.3DXhzE4h/E5ZCCjW4eNTQZCv4eHCXMa', '張志豪', 'STUDENT', 4, '11312004@stu.nqu.edu.tw');
INSERT INTO users (user_id, username, password_hash, full_name, role, dept_id, email) VALUES (33, '11312005', '$2b$12$oYgJc2TrAIdkR8B10U2W9ee0BKuQshOvRsqR7LP2zuoL3IUv6W0qq', '王美華', 'STUDENT', 4, '11312005@stu.nqu.edu.tw');
INSERT INTO users (user_id, username, password_hash, full_name, role, dept_id, email) VALUES (34, '11312006', '$2b$12$B4uvHytF3lhtFY6wtLHliuQKnic/yNYttMsXFqhivjKzO1pA0Q4jy', '李建華', 'STUDENT', 4, '11312006@stu.nqu.edu.tw');
INSERT INTO users (user_id, username, password_hash, full_name, role, dept_id, email) VALUES (35, '11315001', '$2b$12$RB6d6AoIPhnv.hIkOat1E.vqe6HZ12svN7AHpjaxdbeaebsidV8MG', '鄭小玲', 'STUDENT', 5, '11315001@stu.nqu.edu.tw');
INSERT INTO users (user_id, username, password_hash, full_name, role, dept_id, email) VALUES (36, '11315002', '$2b$12$sBiNZhgvcprzB8GFmRp1tO4VN8N3o1e8o8eZ7h/u9e5brQfJrAO9C', '蔡志偉', 'STUDENT', 5, '11315002@stu.nqu.edu.tw');
INSERT INTO users (user_id, username, password_hash, full_name, role, dept_id, email) VALUES (37, '11315003', '$2b$12$.SQB.bgaPvPLuhNVNlyE9uYQqN8H7aCQyYJ9YyXzJ8E4qN8CdXtsK', '林美珍', 'STUDENT', 5, '11315003@stu.nqu.edu.tw');
INSERT INTO users (user_id, username, password_hash, full_name, role, dept_id, email) VALUES (38, '11315004', '$2b$12$H/Y3BITvtw29/Py6qTysJe3J7xyz.9dUhJ/xW0uai.UtcItyRr7wi', '張家榮', 'STUDENT', 5, '11315004@stu.nqu.edu.tw');
INSERT INTO users (user_id, username, password_hash, full_name, role, dept_id, email) VALUES (39, '11315005', '$2b$12$I9v2phUx8h8gjgMbCtlRyekGpbdWbsc5/iL3TN0cSaoakx6sBX1U6', '王小萍', 'STUDENT', 5, '11315005@stu.nqu.edu.tw');
INSERT INTO users (user_id, username, password_hash, full_name, role, dept_id, email) VALUES (40, '11315006', '$2b$12$6ZJY1K41KxdMkEXXHur0Fum6S1Giam7ILU7zy0avHTYwGMVZz1qa2', '李雅芳', 'STUDENT', 5, '11315006@stu.nqu.edu.tw');

-- 管理員帳號
INSERT INTO users (user_id, username, password_hash, full_name, role, dept_id, email) VALUES (41, 'admin', '$2b$12$urbvCdXhA6/fQwc9OwxD3eC65ZBL41ZugNyavGLVm02q7NhgeU1Yi', '系統管理員', 'ADMIN', 1, 'admin@nqu.edu.tw');
INSERT INTO users (user_id, username, password_hash, full_name, role, dept_id, email) VALUES (42, 'dean', '$2b$12$bS5XqephYA2UB06X8HhoZO8MdaUKPI8WcikYSTWCfh1tOY.FsQcvW', '教務長', 'ADMIN', 1, 'dean@nqu.edu.tw');

-- 課程資料 (113學年第1學期)
INSERT INTO courses (course_id, course_code, academic_year, semester, course_name, teacher_id, credits, capacity, enrolled_count, dept_id) VALUES (1, 'CSIE301', 113, 1, '資料結構', 1, 3, 30, 0, 1);
INSERT INTO courses (course_id, course_code, academic_year, semester, course_name, teacher_id, credits, capacity, enrolled_count, dept_id) VALUES (2, 'CSIE302', 113, 1, '演算法', 2, 3, 37, 0, 1);
INSERT INTO courses (course_id, course_code, academic_year, semester, course_name, teacher_id, credits, capacity, enrolled_count, dept_id) VALUES (3, 'CSIE401', 113, 1, '計算機網路', 1, 3, 34, 0, 1);
INSERT INTO courses (course_id, course_code, academic_year, semester, course_name, teacher_id, credits, capacity, enrolled_count, dept_id) VALUES (4, 'CSIE402', 113, 1, '資料庫系統', 1, 3, 51, 0, 1);
INSERT INTO courses (course_id, course_code, academic_year, semester, course_name, teacher_id, credits, capacity, enrolled_count, dept_id) VALUES (5, 'CSIE201', 113, 1, '程式設計', 1, 3, 48, 0, 1);
INSERT INTO courses (course_id, course_code, academic_year, semester, course_name, teacher_id, credits, capacity, enrolled_count, dept_id) VALUES (6, 'EE301', 113, 1, '電路學', 4, 3, 31, 0, 2);
INSERT INTO courses (course_id, course_code, academic_year, semester, course_name, teacher_id, credits, capacity, enrolled_count, dept_id) VALUES (7, 'EE302', 113, 1, '電子學', 3, 3, 32, 0, 2);
INSERT INTO courses (course_id, course_code, academic_year, semester, course_name, teacher_id, credits, capacity, enrolled_count, dept_id) VALUES (8, 'EE401', 113, 1, '控制系統', 3, 3, 37, 0, 2);
INSERT INTO courses (course_id, course_code, academic_year, semester, course_name, teacher_id, credits, capacity, enrolled_count, dept_id) VALUES (9, 'ME301', 113, 1, '機械設計', 5, 3, 47, 0, 3);
INSERT INTO courses (course_id, course_code, academic_year, semester, course_name, teacher_id, credits, capacity, enrolled_count, dept_id) VALUES (10, 'ME302', 113, 1, '熱力學', 5, 3, 52, 0, 3);
INSERT INTO courses (course_id, course_code, academic_year, semester, course_name, teacher_id, credits, capacity, enrolled_count, dept_id) VALUES (11, 'BA201', 113, 1, '企業管理', 8, 3, 37, 0, 4);
INSERT INTO courses (course_id, course_code, academic_year, semester, course_name, teacher_id, credits, capacity, enrolled_count, dept_id) VALUES (12, 'BA301', 113, 1, '會計學', 8, 3, 48, 0, 4);
INSERT INTO courses (course_id, course_code, academic_year, semester, course_name, teacher_id, credits, capacity, enrolled_count, dept_id) VALUES (13, 'BA302', 113, 1, '人力資源管理', 8, 3, 55, 0, 4);
INSERT INTO courses (course_id, course_code, academic_year, semester, course_name, teacher_id, credits, capacity, enrolled_count, dept_id) VALUES (14, 'TM201', 113, 1, '觀光英語', 9, 3, 54, 0, 5);
INSERT INTO courses (course_id, course_code, academic_year, semester, course_name, teacher_id, credits, capacity, enrolled_count, dept_id) VALUES (15, 'TM301', 113, 1, '旅館管理', 9, 3, 52, 0, 5);

-- 上課時間
INSERT INTO class_schedules (schedule_id, course_id, day_of_week, start_period, end_period, location) VALUES (1, 1, 1, 6, 8, '人文大樓 C220');
INSERT INTO class_schedules (schedule_id, course_id, day_of_week, start_period, end_period, location) VALUES (2, 2, 1, 6, 8, '人文大樓 A212');
INSERT INTO class_schedules (schedule_id, course_id, day_of_week, start_period, end_period, location) VALUES (3, 3, 3, 4, 6, '理工大樓 C245');
INSERT INTO class_schedules (schedule_id, course_id, day_of_week, start_period, end_period, location) VALUES (4, 4, 5, 6, 8, '人文大樓 A294');
INSERT INTO class_schedules (schedule_id, course_id, day_of_week, start_period, end_period, location) VALUES (5, 4, 4, 1, 3, '人文大樓 E216');
INSERT INTO class_schedules (schedule_id, course_id, day_of_week, start_period, end_period, location) VALUES (6, 5, 3, 4, 6, '理工大樓 E238');
INSERT INTO class_schedules (schedule_id, course_id, day_of_week, start_period, end_period, location) VALUES (7, 6, 5, 10, 12, '理工大樓 C274');
INSERT INTO class_schedules (schedule_id, course_id, day_of_week, start_period, end_period, location) VALUES (8, 6, 4, 3, 5, '管理大樓 A206');
INSERT INTO class_schedules (schedule_id, course_id, day_of_week, start_period, end_period, location) VALUES (9, 7, 4, 3, 5, '管理大樓 C211');
INSERT INTO class_schedules (schedule_id, course_id, day_of_week, start_period, end_period, location) VALUES (10, 7, 5, 6, 8, '人文大樓 A249');
INSERT INTO class_schedules (schedule_id, course_id, day_of_week, start_period, end_period, location) VALUES (11, 8, 2, 6, 8, '管理大樓 C221');
INSERT INTO class_schedules (schedule_id, course_id, day_of_week, start_period, end_period, location) VALUES (12, 9, 1, 6, 8, '人文大樓 B286');
INSERT INTO class_schedules (schedule_id, course_id, day_of_week, start_period, end_period, location) VALUES (13, 10, 3, 4, 6, '理工大樓 E282');
INSERT INTO class_schedules (schedule_id, course_id, day_of_week, start_period, end_period, location) VALUES (14, 11, 4, 1, 3, '人文大樓 B221');
INSERT INTO class_schedules (schedule_id, course_id, day_of_week, start_period, end_period, location) VALUES (15, 12, 3, 8, 10, '理工大樓 C282');
INSERT INTO class_schedules (schedule_id, course_id, day_of_week, start_period, end_period, location) VALUES (16, 13, 4, 1, 3, '人文大樓 B288');
INSERT INTO class_schedules (schedule_id, course_id, day_of_week, start_period, end_period, location) VALUES (17, 13, 3, 8, 10, '理工大樓 A230');
INSERT INTO class_schedules (schedule_id, course_id, day_of_week, start_period, end_period, location) VALUES (18, 14, 1, 6, 8, '人文大樓 D235');
INSERT INTO class_schedules (schedule_id, course_id, day_of_week, start_period, end_period, location) VALUES (19, 15, 4, 3, 5, '管理大樓 E292');

-- 選課紀錄
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (1, 11, 1, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (2, 11, 7, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (3, 11, 12, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (4, 12, 4, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (5, 12, 5, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (6, 12, 12, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (7, 13, 1, 'DROPPED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (8, 13, 11, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (9, 14, 13, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (10, 14, 10, 'DROPPED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (11, 15, 3, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (12, 15, 6, 'DROPPED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (13, 15, 2, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (14, 15, 12, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (15, 16, 7, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (16, 16, 14, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (17, 16, 5, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (18, 16, 12, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (19, 17, 6, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (20, 17, 2, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (21, 17, 3, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (22, 17, 8, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (23, 18, 13, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (24, 18, 2, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (25, 18, 5, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (26, 19, 13, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (27, 19, 14, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (28, 19, 5, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (29, 19, 8, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (30, 20, 12, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (31, 20, 15, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (32, 20, 1, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (33, 20, 5, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (34, 21, 1, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (35, 21, 13, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (36, 21, 3, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (37, 21, 8, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (38, 22, 11, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (39, 22, 1, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (40, 22, 8, 'DROPPED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (41, 22, 12, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (42, 23, 8, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (43, 23, 7, 'DROPPED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (44, 24, 8, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (45, 24, 3, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (46, 24, 1, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (47, 25, 5, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (48, 25, 6, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (49, 25, 2, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (50, 26, 4, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (51, 26, 8, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (52, 26, 1, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (53, 27, 4, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (54, 27, 1, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (55, 27, 3, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (56, 28, 9, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (57, 28, 7, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (58, 29, 8, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (59, 29, 12, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (60, 29, 11, 'DROPPED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (61, 29, 3, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (62, 30, 12, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (63, 30, 3, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (64, 30, 14, 'DROPPED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (65, 31, 11, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (66, 31, 10, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (67, 31, 8, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (68, 31, 2, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (69, 32, 5, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (70, 32, 12, 'DROPPED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (71, 32, 11, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (72, 32, 2, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (73, 33, 10, 'DROPPED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (74, 33, 11, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (75, 33, 12, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (76, 34, 10, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (77, 34, 2, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (78, 34, 8, 'DROPPED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (79, 35, 1, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (80, 35, 6, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (81, 35, 12, 'DROPPED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (82, 36, 13, 'DROPPED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (83, 36, 10, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (84, 36, 9, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (85, 36, 8, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (86, 37, 7, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (87, 37, 3, 'DROPPED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (88, 38, 6, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (89, 38, 1, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (90, 38, 10, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (91, 39, 13, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (92, 39, 5, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (93, 39, 2, 'ENROLLED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (94, 40, 3, 'DROPPED');
INSERT INTO enrollments (enrollment_id, student_id, course_id, status) VALUES (95, 40, 14, 'ENROLLED');

-- 成績資料
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (1, 1, 86.6, 95.68, 92.05, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (2, 2, 58.71, 52.88, 55.21, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (3, 3, 53.34, 85.75, 72.79, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (4, 4, 54.4, 74.18, 66.27, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (5, 5, 71.77, 53.66, 60.9, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (6, 6, 65.57, 96.78, 84.3, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (7, 7, 92.4, 53.56, 69.1, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (8, 8, 52.39, 49.49, 50.65, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (9, 9, 70.35, 78.39, 75.17, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (10, 10, 60.35, 73.18, 68.05, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (11, 11, 55.32, 82.3, 71.51, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (12, 12, 75.29, 61.96, 67.29, FALSE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (13, 13, 97.25, 48.01, 67.71, FALSE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (14, 14, 95.38, 87.2, 90.47, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (15, 15, 63.89, 51.6, 56.52, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (16, 16, 70.67, 52.11, 59.53, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (17, 17, 61.05, 75.73, 69.86, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (18, 18, 67.0, 66.84, 66.9, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (19, 19, 70.94, 70.29, 70.55, FALSE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (20, 20, 65.03, 68.61, 67.18, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (21, 21, 80.73, 60.92, 68.84, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (22, 22, 96.38, 54.45, 71.22, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (23, 23, 72.08, 82.93, 78.59, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (24, 24, 70.96, 50.82, 58.88, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (25, 25, 69.22, 49.33, 57.29, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (26, 26, 85.8, 57.19, 68.63, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (27, 27, 53.67, 79.83, 69.37, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (28, 28, 59.31, 87.69, 76.34, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (29, 29, 95.99, 80.5, 86.7, FALSE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (30, 30, 54.93, 59.08, 57.42, FALSE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (31, 31, 57.34, 86.75, 74.99, FALSE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (32, 32, 95.66, 79.54, 85.99, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (33, 33, 77.06, 76.87, 76.95, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (34, 34, 92.34, 80.36, 85.15, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (35, 35, 65.51, 98.4, 85.24, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (36, 36, 71.11, 70.79, 70.92, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (37, 37, 88.22, 77.53, 81.81, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (38, 38, 53.56, 70.4, 63.66, FALSE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (39, 39, 67.7, 60.79, 63.55, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (40, 40, 96.91, 49.97, 68.75, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (41, 41, 68.46, 76.92, 73.54, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (42, 42, 85.47, 47.26, 62.54, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (43, 43, 77.44, 55.35, 64.19, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (44, 44, 74.07, 97.67, 88.23, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (45, 45, 88.93, 91.06, 90.21, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (46, 46, 54.05, 80.54, 69.94, FALSE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (47, 47, 83.97, 99.5, 93.29, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (48, 48, 79.27, 65.01, 70.71, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (49, 49, 68.6, 87.6, 80.0, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (50, 50, 52.51, 79.7, 68.82, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (51, 51, 65.83, 75.69, 71.75, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (52, 52, 62.1, 91.84, 79.94, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (53, 53, 78.93, 53.27, 63.53, FALSE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (54, 54, 81.85, 95.42, 89.99, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (55, 55, 81.49, 81.42, 81.45, FALSE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (56, 56, 84.02, 49.66, 63.4, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (57, 57, 80.89, 63.07, 70.2, FALSE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (58, 58, 83.74, 97.09, 91.75, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (59, 59, 93.8, 50.14, 67.6, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (60, 60, 74.41, 46.0, 57.36, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (61, 61, 95.66, 63.8, 76.54, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (62, 62, 59.22, 100.0, 83.69, FALSE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (63, 63, 64.2, 88.35, 78.69, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (64, 64, 75.91, 85.63, 81.74, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (65, 65, 81.77, 93.2, 88.63, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (66, 66, 78.67, 53.48, 63.56, FALSE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (67, 67, 83.26, 79.36, 80.92, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (68, 68, 84.62, 47.4, 62.29, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (69, 69, 84.54, 98.33, 92.81, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (70, 70, 86.11, 88.11, 87.31, FALSE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (71, 71, 61.48, 98.11, 83.46, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (72, 72, 93.39, 55.67, 70.76, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (73, 73, 77.38, 69.23, 72.49, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (74, 74, 87.35, 72.66, 78.54, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (75, 75, 57.78, 55.98, 56.7, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (76, 76, 91.9, 47.87, 65.48, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (77, 77, 67.82, 96.39, 84.96, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (78, 78, 74.76, 51.86, 61.02, FALSE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (79, 79, 57.69, 69.71, 64.9, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (80, 80, 89.89, 50.04, 65.98, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (81, 81, 89.2, 93.65, 91.87, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (82, 82, 69.92, 66.8, 68.05, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (83, 83, 68.54, 49.49, 57.11, FALSE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (84, 84, 65.3, 50.45, 56.39, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (85, 85, 66.09, 53.03, 58.25, FALSE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (86, 86, 94.04, 70.99, 80.21, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (87, 87, 86.42, 70.8, 77.05, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (88, 88, 93.48, 46.05, 65.02, FALSE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (89, 89, 57.18, 96.71, 80.9, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (90, 90, 70.32, 87.69, 80.74, FALSE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (91, 91, 55.85, 58.11, 57.21, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (92, 92, 79.89, 48.45, 61.03, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (93, 93, 73.99, 74.48, 74.28, TRUE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (94, 94, 77.6, 84.52, 81.75, FALSE);
INSERT INTO grades (grade_id, enrollment_id, midterm_score, final_score, total_score, is_submitted) VALUES (95, 95, 50.08, 64.4, 58.67, TRUE);

-- === 假資料統計 ===
-- 科系: 5 筆
-- 教師: 10 筆
-- 學生: 30 筆
-- 管理員: 2 筆
-- 課程: 15 筆
-- 上課時間: 19 筆
-- 選課紀錄: 95 筆
-- 成績: 95 筆
